name: MLOps Training Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - "data/**"
      - "src/train.py"
      - "src/data_validate.py"
      - "src/evaluate.py"
      - "requirements.txt"

jobs:
  train-validate-evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Data
        run: |
          python src/data_validate.py

      - name: Train Model
        run: |
          python src/train.py

      - name: Evaluate Model
        run: |
          python src/evaluate.py