name: MLOps CI Pipeline

on:
  workflow_run:
    workflows: ["MLOps Training Pipeline"]
    types:
      - completed

jobs:
  build-test-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      
      # Step 4: Test Hugging Face repo access
      - name: Test Hugging Face repo access
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          python - <<EOF
          from huggingface_hub import list_repo_files
          repo_id = "Onkar000007/spam-mlops-model"
          try:
              files = list_repo_files(repo_id, token="${HUGGINGFACE_TOKEN}")
              print("Files in repo:", files)
              if "model.pkl" not in files:
                  raise FileNotFoundError("model.pkl not found in the repo!")
          except Exception as e:
              print(f"Error accessing Hugging Face repo: {e}")
              exit(1)
          EOF

      # Step 5: Download model from Hugging Face Hub
      - name: Download model from Hugging Face Hub
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          python - <<EOF
          from huggingface_hub import hf_hub_download
          repo_id = "Onkar000007/spam-mlops-model"
          filename = "model.pkl"
          try:
              model_path = hf_hub_download(
                  repo_id=repo_id,
                  filename=filename,
                  token="${HUGGINGFACE_TOKEN}"
              )
              print(f"Model downloaded to {model_path}")
          except Exception as e:
              print(f"Failed to download model: {e}")
              exit(1)
          EOF

      # Step 6: Run API tests
      - name: Run API tests
        run: pytest -v

      # Step 7: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 8: Build Docker image
      - name: Build Docker image
        run: docker build -t onkarnanavare/spam-mlops:latest .

      # Step 9: Push Docker image
      - name: Push Docker image
        run: docker push onkarnanavare/spam-mlops:latest