name: MLOps CI Pipeline

on:
  workflow_run:
    workflows: ["MLOps Training Pipeline"]
    types:
      - completed

jobs:
  build-test-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Download model from Hugging Face Hub
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          python - <<EOF
          from huggingface_hub import hf_hub_download
          model_path = hf_hub_download(
              repo_id="your-username/spam-mlops-model",
              filename="model.pkl",
              token="${HUGGINGFACE_TOKEN}"
          )
          print(f"Model downloaded to {model_path}")
          EOF

      - name: Run API tests
        run: pytest -v

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t onkarnanavare/spam-mlops:latest .

      - name: Push Docker image
        run: docker push onkarnanavare/spam-mlops:latest